from pathlib import Path

# Repair OpenAPI projection so AuthorizationProvenance stays in parity with the
# canonical Rust schema generated by issue93_patch.py.
p = Path('integrations/openapi.yaml')
s = p.read_text(encoding='utf-8')
old = '''    AuthorizationProvenance:\n      type: object\n      additionalProperties: false\n      required: [participant_id, intent_id, source, reason, grant_id]\n      description: Historical non-secret authorization decision persisted at execution commit time.\n      properties:\n        participant_id:\n          $ref: '#/components/schemas/ParticipantId'\n        intent_id:\n          $ref: '#/components/schemas/IntentId'\n        source:\n          type: string\n        reason:\n          type: string\n        grant_id:\n          type: [integer, 'null']\n          minimum: 1\n'''
new = '''    AuthorizationProvenance:\n      type: object\n      additionalProperties: false\n      required: [participant_id, intent_id, principal, capability, resource, source, reason, grant_id]\n      description: Historical non-secret authorization decision and admitted request context persisted at execution commit time. Legacy principal/resource fields may remain null when they cannot be recovered without policy reconstruction.\n      properties:\n        participant_id:\n          $ref: '#/components/schemas/ParticipantId'\n        intent_id:\n          $ref: '#/components/schemas/IntentId'\n        principal:\n          anyOf:\n            - $ref: '#/components/schemas/Principal'\n            - type: 'null'\n        capability:\n          type: [string, 'null']\n        resource:\n          type: [string, 'null']\n        source:\n          type: string\n        reason:\n          type: string\n        grant_id:\n          type: [integer, 'null']\n          minimum: 1\n'''
if old not in s:
    raise SystemExit('OpenAPI AuthorizationProvenance block not found')
s = s.replace(old, new, 1)
p.write_text(s, encoding='utf-8')

# Keep the participant-isolation fixture valid under the stronger historical
# authorization-context invariant.
p = Path('src/execution_integrity_tests.rs')
s = p.read_text(encoding='utf-8')
old = '''            "INSERT INTO execution_authorization_provenance\n                (participant_id, intent_id, source, reason, grant_id)\n             VALUES (?1, 'shared-intent', 'implicit_authority', 'implicit_participant_hmac', NULL)",\n            [participant],\n'''
new = '''            "INSERT INTO execution_authorization_provenance\n                (participant_id, intent_id, principal_provider, principal_subject,\n                 capability, resource, source, reason, grant_id)\n             VALUES (?1, 'shared-intent', 'participant-hmac', ?1,\n                     'post_message', 'blackboard-lounge',\n                     'implicit_authority', 'implicit_participant_hmac', NULL)",\n            [participant],\n'''
if old not in s:
    raise SystemExit('shared-intent authorization fixture not found')
s = s.replace(old, new, 1)
p.write_text(s, encoding='utf-8')

# Keep the HTTP audit fixture valid under the stronger historical
# authorization-context invariant. Ingress participant_id is also populated
# explicitly so the fixture represents fresh post-#87 evidence.
p = Path('src/http_contract_tests.rs')
s = p.read_text(encoding='utf-8')
old = '''        "INSERT INTO execution_authorization_provenance\n            (participant_id, intent_id, source, reason, grant_id)\n         VALUES (?1, 'intent-http-audit', 'implicit_authority', 'implicit_human_web', NULL)",\n        [&fixture.participant_id],\n'''
new = '''        "INSERT INTO execution_authorization_provenance\n            (participant_id, intent_id, principal_provider, principal_subject,\n             capability, resource, source, reason, grant_id)\n         VALUES (?1, 'intent-http-audit', 'human-web', ?1,\n                 'post_message', 'blackboard-lounge',\n                 'implicit_authority', 'implicit_human_web', NULL)",\n        [&fixture.participant_id],\n'''
if old not in s:
    raise SystemExit('HTTP authorization fixture not found')
s = s.replace(old, new, 1)
old = '''        "INSERT INTO ingress_provenance\n            (delivery_id, intent_id, transport, external_ref, principal_provider, principal_subject)\n         VALUES ('delivery-http-audit', 'intent-http-audit', 'rest', 'ref', 'human-web', ?1)",\n        [&fixture.participant_id],\n'''
new = '''        "INSERT INTO ingress_provenance\n            (delivery_id, participant_id, intent_id, transport, external_ref,\n             principal_provider, principal_subject)\n         VALUES ('delivery-http-audit', ?1, 'intent-http-audit', 'rest', 'ref', 'human-web', ?1)",\n        [&fixture.participant_id],\n'''
if old not in s:
    raise SystemExit('HTTP ingress fixture not found')
s = s.replace(old, new, 1)
p.write_text(s, encoding='utf-8')
